#!/bin/sh

# put this file in your ~/bin directory
# make sure this file is executable or run: chmod +x ~/bin/tab
# make sure ~/bin is in your $PATH
# if not, add the following line (without the #) to your ~/.zshrc or ~/.bash_profile
# export PATH=$PATH:~/bin

printstring=""
first=1
while [ "$1" != "" ]; do
    if [ $first == 1 ]; then
        printstring="$"$1
        first=0
    else
        printstring=$printstring'"\t"'"$"$1
    fi
    shift;
done;
awk -F"\t" '{print '$printstring'}'
